### ISSUE TITLE
spine 案例武器穿帮了

### ISSUE THREAD

**Issue by errnull** [galacean/oasis-engine.github.io#564]
https://oasisengine.cn/#/docs/latest/zh/spine.zh-CN
官网spine案例武器穿帮了
![L1VzZXJzL3lhbmdzaS9MaWJyYXJ5L0FwcGxpY2F0aW9uIFN1cHBvcnQvaURpbmdUYWxrLzI5MTY1MjA3NjRfdjIvSW1hZ2VGaWxlcy8xNjY5MTcyODIyNDMzX0Q2RTk3RUU0LTk0QkUtNDM4Mi1CMjZCLTVFM0IyNTk0RDVFMC5wbmc=](https://user-images.githubusercontent.com/28481578/203690100-c5673035-6318-4af5-a0c3-754dcc6e7407.png)

**Comment by johanzhu** [comment]
武器的层级在衣服的层级之下，再加上扳手的图片过长导致穿帮了。
galacean-spine 这个换皮的API比较hack所以会有这种问题。
用 spine 官方的API换皮，换部件不会有这种问题的。
