### ISSUE TITLE
jsdelivr在国内访问速度不佳，

### ISSUE THREAD

**Issue by eatfishs** [galacean/oasis-engine.github.io#703]
国内访问官网经常速度不佳
![企业微信截图_16778079911499](https://user-images.githubusercontent.com/45836182/222611784-b16e5a90-0f30-4706-ae89-6c55e936ca67.png)

**Comment by eyworldwide** [comment]
官网的域名从 oasisengine.cn 改成了 https://galacean.antgroup.com/ ，同时官网的托管也从 github pages 转移到了我们自己的服务器上，官网打不开或者打开慢的问题已经彻底解决。
